name: CPP Terraform Azure Policy Management
trigger: none
pr:
  - master

resources:
  repositories:
    - repository: cppAzureDevOpsTemplates
      type: github
      name: hmcts/cpp-azure-devops-templates
      ref: "DTSPO-26989-flexible-stages"
      endpoint: "hmcts"

parameters:
  - name: tfversion
    default: 1.12.2
  - name: agentPool
    values:
      - "MDV-ADO-AGENTS-01"
      - "MPD-ADO-AGENTS-01"
    default: "MDV-ADO-AGENTS-01"
  - name: platform
    values:
      - "nonlive"
      - "live"
    default: "nonlive"
  - name: targetResources
    default: null
  - name: enableDebug
    displayName: Enable Debug run
    type: string
    default: false
    values:
      - "true"
      - "false"

variables:
  - name: backendConfigFile
    value: backend_config/${{ parameters.platform }}.conf
  - ${{ if eq(parameters.platform, 'nonlive') }}:
      - name: azureServiceConnection
        value: ado_nonlive_workload_identity
      - name: vaultAdminCredentialsVarGroup
        value: cpp-nonlive-vault-admin
  - ${{ if eq(parameters.platform, 'live') }}:
      - name: azureServiceConnection
        value: ado_live_workload_identity
      - name: vaultAdminCredentialsVarGroup
        value: cpp-live-vault-admin

stages:
  - stage: precommit
    pool:
      name: ${{ parameters.agentPool }}
    jobs:
      - job: pre
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - template: steps/terraform/terraform-precommit.yaml@cppAzureDevOpsTemplates
            parameters:
              tfversion: ${{ parameters.tfversion }}

  - ${{ if eq(variables['Build.Reason'], 'Manual') }}:
      - template: pipelines/terraform-ws-plan-and-apply.yaml@cppAzureDevOpsTemplates
        parameters:
          tfversion: ${{ parameters.tfversion }}
          azureServiceConnection: ${{ variables.azureServiceConnection }}
          vaultAdminCredentialsVarGroup: ${{ variables.vaultAdminCredentialsVarGroup }}
          platform: ${{ parameters.platform }}
          environment: ${{ parameters.platform }}
          agentPool: ${{ parameters.agentPool }}
          targetResources: ${{ parameters.targetResources }}

  # Trigger compliance scan
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - stage: trigger_scan
      displayName: Trigger Policy State Scan
      dependsOn:
        - apply_nlv
        - apply_lve
      pool:
        name: MDV-ADO-AGENTS-01
      jobs:
        - job: scan
          steps:
            - task: AzureCLI@2
              displayName: Trigger Policy State Scan - Non Live
              inputs:
                scriptType: bash
                azureSubscription: 'ado_nonlive_workload_identity'
                scriptLocation: inlineScript
                inlineScript: |
                  az policy state scan --subscription 0511a7fe-771b-4ffa-9348-c59e9c4a87bd
                  az policy state scan --subscription 8cdb5405-7535-4349-92e9-f52bddc7833a
                  az policy state scan --subscription e6b5053b-4c38-4475-a835-a025aeb3d8c7
            - task: AzureCLI@2
              displayName: Trigger Policy State Scan - Live
              inputs:
                scriptType: bash
                azureSubscription: 'ado_live_workload_identity'
                scriptLocation: inlineScript
                inlineScript: |
                  az policy state scan --subscription e7819cdc-66af-4611-9dba-b9958e5b6d7d
                  az policy state scan --subscription 9ab65d81-930d-4cc0-a93d-367e14676bc0
